### ISSUE TITLE
Como resolvo conflitos?

### ISSUE THREAD

**Issue by LarisseLima** [atomiccstudio/referencias-tecnologia-atomicc#23]
Olá,não estou conseguindo trazer informações da master para minha máquina.
Com isso ta dando conflitos. Como resolvo isso ?
;)

**Comment by atomiccstudio** [comment]
Oii @LarisseLima Tu tem que rodar o comando **git pull origin main** 
Esse repositório, assim como os mais novos do github, não usam mais a palavra 'master' pra se referir a branch principal e sim 'main'. Tu pode tentar rodar esse comando e nos dizer se funcionou?  Muito obrigada por contribuir *-*

**Comment by LarisseLima** [comment]
Sim, reparei nessa coisa da main.
No meu caso,aparece isso e não atualiza >>>

$ git pull origin main
From https://github.com/LarisseLima/referencias-tecnologia-atomicc
 * branch              main       -> FETCH_HEAD
Already up to date.

**Comment by LarisseLima** [comment]
Consegui agora, pois o link "origin" estava apontando pro meu repo e não para o original.
Obrigada :)
